name: 'Clog - Auto Changelog'
description: 'Put your Pull Requests in your Release Notes'
author: 'coffeedoughnuts'
branding:
  icon: 'package'
  color: 'purple'
inputs:
  githubToken:
    description: 'Your GitHub Token'
    required: true
  autoVersion:
    description: 'Should the draft have an auto-incremented version'
    required: false
    default: 'false'
  shortcut:
    description: 'If you want Shortcut IDs linked, provide your workspace name'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'